(setf *SUPPRESS-SIMILAR-CONSTANT-REDEITION-WARNING* t)

(defpackage :ANDREW-HUBER)
(in-package :ANDREW-HUBER)

(defun theorize (effect instigator victim player cards game)
	(print "theorize")
	(cond
		((eq effect 'coup::Block) (theorize-block effect instigator victim player cards game))
		((eq effect 'coup::Challenge) (theorize-challenge effect instigator victim player cards game))
		((eq effect 'coup::Assassinate) (theorize-assassinate effect instigator victim player cards game))
		((eq effect 'coup::Coup) (theorize-coup effect instigator victim player cards game))
		((eq effect 'coup::Exchange) (theorize-exchange effect instigator victim player cards game))
		((eq effect 'coup::ForeignAid) (theorize-foreign-aid effect instigator victim player cards game))
		((eq effect 'coup::Income) (theorize-income effect instigator victim player cards game))
		((eq effect 'coup::Steal) (theorize-steal effect instigator victim player cards game))
		((eq effect 'coup::Tax) (theorize-tax effect instigator victim player cards game))
		(T (progn
			(print "Invalid effect of...")
			(print effect)
			(error "Quitting" )))))

(defun theorize-block (effect instigator victim player cards game)
	(print "theorize-block")
	(setf lst nil)
	(setf game-copy (copy-game game))
	(push-to-stack (my-game-step-stack game-copy) (makeinstance 'my-step :effect effect :instigator instigator :victim victim :player player :cards cards))
	(setf lst (append lst (theorize-challenge 'Block victim instigator instigator player cards game-copy)))
	lst)

(defun theorize-challenge (effect instigator victim player cards game)
	(print "theorize-challenge")
	(setf lst nil)
	(if (not (null (get-card (my-step-effect (peek-from-stack (my-game-step-stack game))))))
		(if (players-equal player (current-player-object game))
			(progn
				(setf game-copy (copy-game game))
				(push-to-stack (my-game-step-stack game-copy) (make-instance 'my-step :effect effect :instigator instigator :victim victim :player player :cards cards))
				(setf lst (cons game-copy lst))))
		(progn
			(setf copy (copy-game game))
			(push-to-stack (my-game-step-stack copy) (make-instance 'my-step :effect effect :instigator instigator :victim victim :player player :cards cards))
			(setf lst (cons copy lst))))
	(setf copy (copy-game game))
	(setf lst (cons game lst))
	lst)

(defun theorize-assassinate (effect instigator victim player cards game)
	(print "theorize-assassinate")
	(theorize-assassinate-generic effect instigator victim player cards game 3))

(defun theorize-assassinate-generic (effect instigator victim player cards game num-coins)
	(print "theorize-assassinate-generic")
	(setf lst nil)
	(if (>= (coup::player-coins instigator) num-coins)
		(progn
			(setf other-players (get-other-players-except game instigator))
			(dolist (other-player other-players)
				(setf possible-cards-to-assasinate nil)
				(if (or (eq cards nil) (> (list-length cards) 1)) 
					(setf possible-cards-to-assassinate (get-possible-cards-to-assassinate game player))
					(setf possible-cards-to-assassinate cards))
				(dolist (possible-card possible-cards-to-assassinate)
					(setf cards (list possible-card))
					(setf lst (append lst (theorize-action effect instigator other-player player cards game)))))))
	lst)

(defun theorize-coup (effect instigator victim player cards game)
	(print "theorize-coup")
	(theorize-assassinate-generic effect instigator victim player cards game 7))

(defun theorize-exchange (effect instigator victim player cards game)
	(print "theorize-exchange")
	(setf lst nil)
	(setf other-players (get-other-players-except game instigator))
	(if (eq (coup::player-handcount instigator) 2)
		(dolist (other-player other-players)
			(dolist (card1 coup::Characters)
				(dolist (card2 coup::Characters)
					(setf cards (list card1 card2))
					(setf lst (append lst (theorize-action effect instigator other-player player cards game)))))))
	lst)

(defun theorize-foreign-aid (effect instigator victim player cards game)
	(print "theorize-foreign-aid")
	(setf other-players (get-other-players-except game instigator))
	(setf lst (list))
	(dolist (other-player other-players)
		(if (not (lost player))
			(setf lst (append lst (theorize-action effect instigator other-player player cards game)))))
	lst)

(defun theorize-income (effect instigator victim player cards game)
	(print "theorize-income")
	(theorize-foreign-aid effect instigator victim player cards game))

(defun theorize-steal (effect instigator victim player cards game)
	(print "theorize-steal")
	(setf lst nil)
	(setf other-players (get-other-players-except game instigator))
	(dolist (other-player other-players)
		(if (>= (coup::player-coins other-player) 2)
			(setf lst (append lst (theorize-action effect instigator other-player player cards game)))))
	lst)

(defun theorize-tax (effect instigator victim player cards game)
	(print "theorize-tax")
	(setf other-players (get-other-players-except game instigator))
	(setf lst nil)
	(dolist (other-player other-players)
		(if (not (lost player))
			(setf lst (append lst (theorize-action effect instigator other-player player cards game)))))
	lst)

(defun theorize-action (eff instigator victim player cards game)
	(print "theorize-action")
	(if (is-action eff)
		(progn
			(setf lst nil)
			(setf counteractions (get-possible-blocks eff))
			;(print "blah1")
			(dolist (counter counteractions)
				(setf gameCopy (copy-game game))
				(push-to-stack (my-game-step-stack game) (make-instance 'my-step :effect eff :instigator instigator :victim victim :player player :cards cards))
				(setf lst (append lst (theorize (get-counteraction counter) victim instigator player cards))))
			;(print "blah2")
			(if (null (get-card eff))
				(progn 
					;(print "blah3")
					(setf gameCopy (copy-game game))
					;(print "blah4")
					(setf step (make-instance 'my-step :effect eff :instigator instigator :victim victim :player player :cards cards))
					;(print "blah5")
					(push-to-stack (my-game-step-stack game) step)
					;(print "blah6")
					(setf lst2 (append lst (theorize 'coup::Challenge victim instigator player cards gameCopy)))
					;(print "blah7")
					(if (null lst)
						(progn 
							;(print "blah8")
							(setf lst lst2))
						(progn
							;(print "blah9")
							(setf lst (append lst lst2))))
					;(print "blah10")
					;(print "blah11")
					lst)
				(progn
					;(print "blah12")
					(setf gameCopy (copy-game game))
					(push-to-stack (my-game-step-stack gameCopy) (make-instance 'my-step :effect eff :instigator instigator :victim victim :player player :cards cards))
					(setf lst (append lst (list gameCopy)))
					lst)))
		(error "parent must be an action")))








