(setf *SUPPRESS-SIMILAR-CONSTANT-REDEITION-WARNING* t)

(defpackage :ANDREW-HUBER)
(in-package :ANDREW-HUBER)

(defun theorize (effect instigator victim player cards game)
	(print "theorize")
	(cond
		((eq effect 'coup::Block) (theorize-block effect instigator victim player cards game))
		((eq effect 'coup::Challenge) (theorize-challenge effect instigator victim player cards game))
		((eq effect 'coup::Assassinate) (theorize-assassinate effect instigator victim player cards game))
		((eq effect 'coup::Coup) (theorize-coup effect instigator victim player cards game))
		((eq effect 'coup::Exchange) (theorize-exchange effect instigator victim player cards game))
		((eq effect 'coup::ForeignAid) (theorize-foreign-aid effect instigator victim player cards game))
		((eq effect 'coup::Income) (theorize-income effect instigator victim player cards game))
		((eq effect 'coup::Steal) (theorize-steal effect instigator victim player cards game))
		((eq effect 'coup::Tax) (theorize-tax effect instigator victim player cards game))
		(T (progn
			(print "Invalid effect of...")
			(print effect)
			(error "Quitting" )))))

(defun theorize-block (effect instigator victim player cards game)
	(print "theorize-block")
	(setq lst nil)
	(setq game-copy (copy-game game))
	(push-to-stack (my-game-step-stack game-copy) (makeinstance 'my-step :effect effect :instigator instigator :victim victim :player player :cards cards))
	(setq lst (append lst (theorize-challenge 'Block victim instigator instigator player cards game-copy)))
	lst)

(defun theorize-challenge (effect instigator victim player cards game)
	(print "theorize-challenge")
	(setf lst (list))
	(if (not (null (get-card (my-step-effect (peek-from-stack (my-game-step-stack game))))))
		(if (players-equal player (current-player-object game))
			(progn
				(setf game-copy (copy-game game))
				(push-to-stack (my-game-step-stack game-copy) (make-instance 'my-step :effect effect :instigator instigator :victim victim :player player :cards cards))
				(setf lst (append lst (list game-copy)))))
		(progn
			(setf copy (copy-game game))
			(push-to-stack (my-game-step-stack copy) (make-instance 'my-step :effect effect :instigator instigator :victim victim :player player :cards cards))
			(setf lst (append lst (list copy)))))
	(setf copy (copy-game game))
	(setf lst (append lst (list game)))
	lst)

(defun theorize-assassinate (effect instigator victim player cards game num-coins)
	(print "theorize-assassinate")
	(theorize-assassinate-generic effect instigator victim player cards game 3))

(defun theorize-assassinate-generic (effect instigator victim player cards game num-coins)
	(print "theorize-assassinate-generic")
	(setq lst nil)
	(if (>= (coup::player-coins instigator) num-coins)
		(progn
			(setq other-players (get-other-players-except game instigator))
			(dolist (other-player other-players)
				(setq possible-cards-to-assasinate nil)
				(if (or (eq cards nil) (> (list-length cards) 1)) 
					(setq possible-cards-to-assassinate (get-possible-cards-to-assassinate game player))
					(setq possible-cards-to-assassinate cards))
				(dolist (possible-card possible-cards-to-assassinate)
					(setq cards (list possible-card))
					(setq cards (append lst (theorize-action parent instigator other-player player cards game lst)))))))
	lst)

(defun theorize-coup (effect instigator victim player cards game)
	(print "theorize-coup")
	(theorize-assassinate-generic effect instigator victim player cards game 7))

(defun theorize-exchange (effect instigator victim player cards game)
	(print "theorize-exchange")
	(setq lst nil)
	(setq other-players (get-other-players-except game instigator))
	(if (eq coup::player-handcount instigator 2)
		(dolist (other-player other-players)
			(dolist (card1 coup::Characters)
				(dolist (card2 coup::Characters)
					(setq cards (list card1 card2))
					(setq (append lst (theorize-action effect instigator other-player player cards game)))))))
	lst)

(defun theorize-foreign-aid (effect instigator victim player cards game)
	(print "theorize-foreign-aid")
	(setq other-players (get-other-players-except game instigator))
	(setq lst (list))
	(dolist (other-player other-players)
		(if (not (lost player))
			(setq lst (append lst (theorize-action effect instigator other-player player cards game)))))
	lst)

(defun theorize-income (effect instigator victim player cards game)
	(print "theorize-income")
	(theorize-foreign-aid effect instigator victim player cards game))

(defun theorize-steal (effect instigator victim player cards game)
	(print "theorize-steal")
	(setq lst nil)
	(setq other-players (get-other-players-except game instigator))
	(dolist (other-player other-players)
		(if (>= (coup::player-coins other-player) 2)
			(setq lst (append lst (theorize-action effect instigator other-player player cards game)))))
	lst)

(defun theorize-tax (effect instigator victim player cards game)
	(print "theorize-tax")
	(setq other-players (get-other-players-except game instigator))
	(setq lst nil)
	(dolist (other-player other-players)
		(if (not (lost player))
			(setq lst (append lst (theorize-action effect instigator other-player player cards game)))))
	lst)

(defun theorize-action (eff instigator victim player cards game)
	(print "theorize-action")
	(if (is-action eff)
		(progn
			(setq lst nil)
			(setq counteractions (get-possible-blocks eff))
			(print "blah1")
			(dolist (counter counteractions)
				(setq gameCopy (copy-game game))
				(push-to-stack (my-game-step-stack game) (make-instance 'my-step :effect eff :instigator instigator :victim victim :player player :cards cards))
				(setq lst (append lst (theorize (get-counteraction counter) victim instigator player cards))))
			(print "blah2")
			(if (null (get-card eff))
				(progn 
					(print "blah3")
					(setq gameCopy (copy-game game))
					(print "blah4")
					(setq step (make-instance 'my-step :effect eff :instigator instigator :victim victim :player player :cards cards))
					(print "blah5")
					(push-to-stack (my-game-step-stack game) step)
					(print "blah6")
					(setq lst (append lst (theorize 'coup::Challenge victim instigator player cards gameCopy))))
				(progn
					(print "blah7")
					(setq gameCopy (copy-game game))
					(my-stack-push (my-game-step-stack gameCopy) (make-instance 'my-step :effect eff :instigator instigator :victim victim :player player :cards cards))
					(setq lst (append lst gameCopy)))))
		(error "parent must be an action")))








